name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 2️⃣ Install requests library
      - name: Install requests
        run: pip install requests

      # 3️⃣ Ping Streamlit App and log status
      - name: Ping Streamlit App and Log Status
        shell: python
        run: |
          import requests
          import time
          from datetime import datetime

          URL = "https://ai-media-analyzer.streamlit.app/"
          LOG_FILE = "ping_log.txt"
          MAX_RETRIES = 3

          with open(LOG_FILE, "a") as f:
              f.write(f"Ping run at {datetime.now()}\n")

          for i in range(MAX_RETRIES):
              try:
                  r = requests.get(URL, timeout=30)
                  status = r.status_code
              except Exception as e:
                  status = None
                  error = str(e)

              with open(LOG_FILE, "a") as f:
                  f.write(f"Attempt {i+1}: Status code: {status if status else 'Error'}\n")
                  if status == 200:
                      f.write("✅ Streamlit app is alive!\n")
                      break
                  else:
                      f.write(f"❌ Streamlit app did not respond properly. Retry {i+1}/{MAX_RETRIES}\n")
                      if status is None:
                          f.write(f"Error: {error}\n")
                      time.sleep(10)
          else:
              with open(LOG_FILE, "a") as f:
                  f.write(f"❌ Streamlit app failed after {MAX_RETRIES} retries.\n")
              exit(1)

      # 4️⃣ Upload log as artifact
      - name: Upload ping log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ping-log
          path: ping_log.txt